### ISSUE TITLE
RuntimeError: Passing `optimizers` is not allowed if Fairscale, Deepspeed or PyTorch FSDP is enabled

### ISSUE THREAD

**Issue by lw3259111** [Liuhong99/Sophia#17]

**Comment by tkella47** [comment]
I am using pytorch lightning and I find that you can indeed pass Sophia, but that using less than 32 bit precision causes errors.

**Comment by lessw2020** [comment]
@lw3259111  - Can you elaborate on how you are passing the optimizer to FSDP and hitting an issue - i.e code snippet? 
I ran it last weekend with FSDP and with FSDP activation checkpointing and BFloat16 mixed precision, worked great.
Depending on what you are doing exactly, it's possible you may need to set use_orig_params=True with FSDP (if you are using param groups, which I did not use). 
Anyway, some context and code snippet would be useful here as I can look into any FSDP issues.

**Comment by lw3259111** [comment]
@lessw2020 
Thanks for your reply. My code is:
``` python
        from transformers import Trainer
        ......
        training_args.optim = None
        no_decay = ["bias", "layer_norm.weight"]
        optimizer_grouped_parameters = [
            {
                "params": [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)],
                "weight_decay": 1e-1,
            },
            {
                "params": [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)],
                "weight_decay": 0.0,
            },
            ]
        optimizer = SophiaG(optimizer_grouped_parameters, lr=training_args.learning_rate, betas=(0.9, 0.999), rho=0.03)
        trainer = Trainer(
        model=model, tokenizer=tokenizer, args=training_args, optimizers=(optimizer, None,),**data_module
        )
```
