### ISSUE TITLE
Evaluation on other domains

### ISSUE THREAD

**Issue by francqz31** [Liuhong99/Sophia#2]
Hello I read the whole paper, it is amazing, the math is well written. And on page 21, it says , "Due to the limitation of computation resources, we leave the application to other domains and models to future works." How soon can we see sophia optimizer for other domains such as computer vision , text-to-speech , reinforcement learning or diffusion with the same 2x speed-up from normal adam optimizer ??

Thanks in advance!

**Comment by Liuhong99** [comment]
Thanks for the interest in our work and this official repo! Sadly we do not have the compute for now to run computer vision, text-to-speech, reinforcement learning or diffusion for now. We will seek collaborations and rely on the community to test Sophia on other domains.
