### ISSUE TITLE
Availability of models?

### ISSUE THREAD

**Issue by ArthurConmy** [Liuhong99/Sophia#21]
Hey! I'm fascinated by work finding competitors to Adam, particularly since from an interoperability perspective it may have some strange properties, such as probably causing [outlier large dimensions in the residual stream](https://transformer-circuits.pub/2023/privileged-basis/index.html). 

Do you have access to any of the Language Models (such as GPT-2 Small sized models) that you trained, to investigate this?

**Comment by Liuhong99** [comment]
Hi! We have the plan to release all model checkpoints, (although it will take some time to figure out the license.)
