### ISSUE TITLE
Sophia on jax

### ISSUE THREAD

**Issue by sglucas** [Liuhong99/Sophia#25]
Hi, thanks for your nice work!

May I ask do you plan to release the jax code and how to use Sophia in jax ?

Best
Lucas

**Comment by Liuhong99** [comment]
The Jax version is already implemented and achieved good partial results on 1.5B and 7B models. I will release the code soon after the 7B run is completed.

**Comment by thegodone** [comment]
Can you do also a tf version ? when you plan to release the jax version ? Can you release H and G versions ?

**Comment by sglucas** [comment]
@Liuhong99 Thanks a lot!

**Comment by Liuhong99** [comment]
The Jax version is now available at https://github.com/stanford-crfm/levanter/blob/e183ec80ec5971b12d4a3fb08a160268de342670/docs/Getting-Started-TPU-VM.md
