### ISSUE TITLE
Can't get good results on smaller models

### ISSUE THREAD

**Issue by tsalex1992** [Liuhong99/Sophia#30]
Thanks for sharing the code, and providing an interesting paper!

I can't seem to reproduce decent results on smaller models on a consumer GPU.
I've tried using the optimizer for a toy task similar to the one present on the nano GPT repo, but it seems that no matter which config I use the model fails to converge. 

I tried using various parameters, but nothing seemed to work - when I plug in adamW instead it just works out of the box.
Can you please provide config for runs of small models on a consumer GPU?

For instance(similar to nanoGPT)
gradient_accumulation_steps = 1
batch_size = 16
block_size = 256  # context of up to 256 previous characters

# baby GPT model :)
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.2

**Comment by Liuhong99** [comment]
I ran n_layer = 6, n_head = 6, n_embd = 384, block size = 1024 before. The result is very good. I'll share the wandb report in this thread later.
