### ISSUE TITLE
Implementing Sophia-H alternative

### ISSUE THREAD

**Issue by thegodone** [Liuhong99/Sophia#42]
can you provide the H version from your paper ?

**Comment by stephankoe** [comment]
You can find a third-party implementation of SophiaH in the [pytorch-optimizer](https://pytorch-optimizers.readthedocs.io/en/latest/optimizer_api.html#sophiah) package.

**Comment by thegodone** [comment]
thanks @stephankoe, Yes, I found it last week but why pytorch-optimizer did not set both ? I am also looking for a "keras/tf" version too...
