### ISSUE TITLE
Incorrect "General Usage" code for Updating Hessian and Solution

### ISSUE THREAD

**Issue by HFarkhari** [Liuhong99/Sophia#44]
**Issue Report: Incorrect "General Usage code" for Updating Hessian**

**Description:**
The current "General Usage" code in the SophiaG repository contains errors, particularly in the part responsible for updating the Hessian. As a result, users may face difficulties while attempting to utilize the code for general purposes. To improve the functionality and allow other PyTorch users to seamlessly test SophiaG by using the sophia.py file, I propose replacing the existing code with the following suggested code snippet.

**Problematic Code (Existing):**
The problematic code for updating the Hessian in the "General Usage" section is causing issues for users trying to test the SophiaG model.

```python
# Existing code with issues in updating Hessian
import torch
from torch import nn
from sophia import SophiaG

#init model loss function and input data
model = Model()
data_loader = ...

#init the optimizer
optimizer = SophiaG(model.parameters(), lr=2e-4, betas=(0.965, 0.99), rho = 0.01, weight_decay=1e-1)

k = 10
iter_num = 0
#training loop
for epoch in range(epochs):
   for X,Y in data_loader:
       if iter_num % k != k - 1:
           # standard training code
           logits, loss = model(X, Y)
           loss.backward()
           optimizer.step(bs=4096)
           optimizer.zero_grad(set_to_none=True)
           iter_num += 1
       else:
           # standard training code
           logits, loss = model(X, Y)
           loss.backward()
           optimizer.step(bs=4096)
           optimizer.zero_grad(set_to_none=True)
           iter_num += 1
           # update hessian EMA
           logits = model(X, None)
           samp_dist = torch.distributions.Categorical(logits=logits)
           y_sample = samp_dist.sample()
           loss_sampled = cross_entropy(logits, y_sample)
           loss_sampled.backward()
           optimizer.update_hessian()
           optimizer.zero_grad(set_to_none=True)
          
```

**Suggested Improvement:**
The following code snippet provides an improved version for updating the Hessian in the "General Usage" section. This code has been tested and verified to work correctly, offering a more reliable experience for users testing the SophiaG model.

```python
# Proposed improved code for updating Hessian
import torch
import torch.nn.functional as F
from sophia import SophiaG

# init model loss function and input data
model = Model()
data_loader = ...

# init the optimizer
optimizer = SophiaG(model.parameters(), lr=2e-4, betas=(0.965, 0.99), rho=0.01, weight_decay=1e-1)

total_bs = len(data_loader)
bs = total_bs * block_size
k = 10
iter_num = -1

# training loop
for epoch in range(epochs):
    for X, Y in data_loader:
        # standard training code
        logits, loss = model(X, Y)
        loss.backward()
        optimizer.step(bs=bs)
        optimizer.zero_grad(set_to_none=True)
        iter_num += 1

        if iter_num % k != k - 1:
            continue
        else:
            # update hessian EMA
            logits, _ = model(X, None)
            samp_dist = torch.distributions.Categorical(logits=logits)
            y_sample = samp_dist.sample()
            loss_sampled = F.cross_entropy(logits.view(-1, logits.size(-1)), y_sample.view(-1), ignore_index=-1)
            loss_sampled.backward()
            optimizer.update_hessian()
            optimizer.zero_grad(set_to_none=True)
            model.zero_grad()
```

**Steps to Reproduce:**

1. Download the "sophia.py" file from the SophiaG repository.
2. Place the downloaded "sophia.py" file in the same folder as your code.
3. Import the SophiaG class from "sophia.py" and utilize it as a template, as provided in the suggested code snippet.

**Expected Behavior:**
Upon updating the Hessian using the suggested improved code, the SophiaG model should function as expected for general use cases, and users should be able to utilize the sophia.py file to test the model seamlessly.

**Additional Information:**
Updating the "General Usage" code with the proposed improvement will enhance the usability of the SophiaG repository for the PyTorch community. This will ensure a smooth experience for users who want to explore and experiment with the SophiaG optimizer.

Please let me know if you require any further information or assistance in resolving this issue.

**Note:** Before merging the changes, it is advisable to have other developers review the code and conduct additional testing to validate its correctness and efficacy.

**Comment by Liuhong99** [comment]
Thanks so much for catching this! I have updated the readme as you suggested.
