### ISSUE TITLE
What are the values of "bs" for vision?

### ISSUE THREAD

**Issue by codonna9** [Liuhong99/Sophia#48]
Hi, 
Thank you for making the implementation of Sophia public. I'd like to try it on image classification problem. But I haven't understood the paper and the implementation well enough to guess the suitable values of "bs" for this problem. Can you suggest some possible values of "bs" to try? 
For example, I got inputs of the following format (batch_size, channel, image_height x image_width). What would be the values of "bs" in this case?

**Comment by tengyuma** [comment]
can we reply to them especially if it's easy?

**Comment by Liuhong99** [comment]
`bs` should be the number of predictions one has in each minibatch. In language modeling, suppose we have n sequences in a batch with T tokens per sequence, then `bs` should be T * n. For image classification, if we have n images per batch, then `bs` should be just n.

**Comment by codonna9** [comment]
Thank you very much for your reply. I'll try that

**Comment by codonna9** [comment]
Thank you very much for your reply. I'll try that
