### ISSUE TITLE
Ambiguous dependency specification

### ISSUE THREAD

**Issue by nalzok** [Liuhong99/Sophia#5]
Can you provide an `environment.yml` or `requirements.txt`? We need the exact version numbers for the purpose of reproducibility. Thanks!

**Comment by Liuhong99** [comment]
Thanks for mentioning this point! We'll update the requirements.txt soon. For reproducibility, as long as you use PyTorch 2.0 with torch.compile and bfloat16, we believe you can reproduce the results in the paper and the wandb report we provide.
